### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.dmfs.httpessentials.types.MediaType org.dmfs.httpessentials.client.HttpRequestEntity.contentType()'

### ISSUE THREAD

**Issue by superjojo79** [dmfs/oauth2-essentials#105]
With the below code, i get an NoSuchMethodError on HttpRequestEntity version 0.20.0, 0.22.0 and 0.22.1

Here is the code 

`HttpRequestExecutor executor = new HttpUrlConnectionExecutor();

        // Create OAuth2 provider
        OAuth2AuthorizationProvider provider = new BasicOAuth2AuthorizationProvider(
                URI.create("https://mock1"),
                URI.create("https://mock2"),
                new Duration(1, 0, 3600) /* default expiration time in case the server doesn't return any */);

        // Create OAuth2 client credentials
        OAuth2ClientCredentials credentials = new BasicOAuth2ClientCredentials(
                "client-id", "client-secret");

        // Create OAuth2 client
        OAuth2Client client = new BasicOAuth2Client(
                provider,
                credentials,
                new LazyUri(new Precoded("http://localhost")) /* Redirect URL */);

        OAuth2AccessToken token = client.accessToken(new ClientCredentialsTokenRequest(), executor);
        System.out.println(token);`

And here is the stacktrace

`Exception in thread "main" java.lang.NoSuchMethodError: 'org.dmfs.httpessentials.types.MediaType org.dmfs.httpessentials.client.HttpRequestEntity.contentType()'
        at org.dmfs.httpessentials.httpurlconnection.HttpUrlConnectionExecutor.sendRequest(HttpUrlConnectionExecutor.java:121)
        at org.dmfs.httpessentials.httpurlconnection.HttpUrlConnectionExecutor.execute(HttpUrlConnectionExecutor.java:80)
        at org.dmfs.httpessentials.executors.useragent.Branded.execute(Branded.java:53)
        at org.dmfs.oauth2.client.BasicOAuth2AuthorizationProvider.accessToken(BasicOAuth2AuthorizationProvider.java:55)
        at org.dmfs.oauth2.client.BasicOAuth2Client.accessToken(BasicOAuth2Client.java:71)`

**Comment by dmfs** [comment]
have you specified a specific version of `org.dmfs:http-client-essentials` in your dependencies? This looks like a version conflict.

**Comment by superjojo79** [comment]
Hi,

Yes I did specify it.

Finally, I found another way to achieve my goal. I can not exclude a JDK
glitch.

Thanks for reply.

Best regards,

Le lun. 1 janv. 2024 à 22:22, Marten Gajda ***@***.***> a
écrit :

**Comment by sbarrax** [comment]
I have the same error specifying these dependencies (but I tried many combinations):

```

        <dependency>
            <groupId>org.dmfs</groupId>
            <artifactId>oauth2-essentials</artifactId>
            <version>0.9</version>
        </dependency>
        <dependency>
            <groupId>org.dmfs</groupId>
            <artifactId>httpurlconnection-executor</artifactId>
            <version>1.22.1</version>
        </dependency>
```
I tried using jdk 17 and 21; the code is identical to the README version.


_EDIT_: switching 'oauth2-essentials' to 0.22.1 leads to success
